service: parallel_large # Must have the same name as the parent directory.

provider:
  name: openwhisk
  ignore_certs: true

functions:
  main:
    handler: ../funcs.main
    parameters:
      owHost: ${file(../config.yaml):openwhisk.host}
      owAuth: ${file(../config.yaml):openwhisk.auth}
      appName: ${self:service}
      collectorHost: ${file(../config.yaml):otelcollector.host}
      functionGraph: ${file(../graph_parallel_large.yaml)}
  f11:
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1  
  f12:
    handler: ../funcs.f
    parameters:
      duration: 500
      alpha: 30
      beta: 0.06  
  f13:
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1    
  f14:
    handler: ../funcs.f
    parameters:
      duration: 400
      alpha: 30
      beta: 0.075 
  f21:
    handler: ../funcs.f
    parameters:
      duration: 400
      alpha: 30
      beta: 0.075
  f22:
    handler: ../funcs.f
    parameters:
      duration: 400
      alpha: 30
      beta: 0.075 
  f23:
    handler: ../funcs.f
    parameters:
      duration: 500
      alpha: 30
      beta: 0.06    
  f24:
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1    
  f31:
    handler: ../funcs.f
    parameters:
      duration: 500
      alpha: 30
      beta: 0.06   
  f32:
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1  
  f33:
    handler: ../funcs.f
    parameters:
      duration: 400
      alpha: 30
      beta: 0.075
  f34:
    handler: ../funcs.f
    parameters:
      duration: 500
      alpha: 30
      beta: 0.06
  f41:
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1 
  f42:
    handler: ../funcs.f
    parameters:
      duration: 500
      alpha: 30
      beta: 0.06
  f43:
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1
  f44:
    handler: ../funcs.f
    parameters:
      duration: 400
      alpha: 30
      beta: 0.075  
  f51:
    handler: ../funcs.f
    parameters:
      duration: 0
      alpha: 1
      beta: 1
  f52:
    handler: ../funcs.f
    parameters:
      duration: 0
      alpha: 1
      beta: 1
  f53:
    handler: ../funcs.f
    parameters:
      duration: 0
      alpha: 1
      beta: 1
  f54:
    handler: ../funcs.f
    parameters:
      duration: 0
      alpha: 1
      beta: 1
      
plugins:
  - serverless-openwhisk

package:
  include:
    - ../funcs.js
    - ../tracing.js