# Host address is only used within serverless functions. 
# Therefore the DNS name is sufficient.
openwhisk:
  host: owdev-nginx.openwhisk.svc.cluster.local:443
  auth: 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
otelcollector:
  host: owtracecollector.default.svc.cluster.local:55681
redis:
  host: owdev-redis.openwhisk.svc.cluster.local:6379