service: fanout_small # Must have the same name as the parent directory.

provider:
  name: openwhisk
  ignore_certs: true

functions:
  main:
    handler: ../funcs.main
    parameters:
      owHost: ${file(../config.yaml):openwhisk.host}
      owAuth: ${file(../config.yaml):openwhisk.auth}
      appName: ${self:service}
      collectorHost: ${file(../config.yaml):otelcollector.host}
      functionGraph: ${file(../graph_fanout_small.yaml)}
  f1: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1
  f21: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1 
  f22: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1
  f23: 
    handler: ../funcs.f
    parameters:
      duration: 400
      alpha: 30
      beta: 0.075 
  f24: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1
  f25: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1
  f3: 
    handler: ../funcs.f
    parameters:
      duration: 500
      alpha: 30
      beta: 0.06    
  f41: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1 
  f42: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1 
  f43: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1 
  f44: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1
  f45: 
    handler: ../funcs.f
    parameters:
      duration: 300
      alpha: 30
      beta: 0.1
      
plugins:
  - serverless-openwhisk

package:
  include:
    - ../funcs.js
    - ../tracing.js